### ISSUE TITLE
Definition of STRICT on Windows builds is incompatible with Windows.h

### ISSUE THREAD

**Issue by randomascii** [aawc/unrar#11]
In os.hpp there is a line of code that says "#define STRICT"

https://github.com/aawc/unrar/blob/master/os.hpp#L25

Unfortunately that is incompatible with the Windows 10 SDK, from at least version 10.0.15063.0 onwards. There, in minwindef.h, the definition is:

#ifndef STRICT
#define STRICT 1
#endif

Depending on the order in which these statements are reached this may be a build break. That is, if minwindef.h is reached first then the compiler will issue this warning:

unrar/src/os.hpp(25,9):  error: 'STRICT' macro redefined [-Werror,-Wmacro-redefined]

Changing the line to #define STRICT 1 would improve compatibility.

**Comment by aawc** [comment]
Thanks for the report, @randomascii 
I'll make this change and get it reviewed by the current maintainer.
