### ISSUE TITLE
Update source

### ISSUE THREAD

**Issue by xiva-wgt** [aawc/unrar#17]
Hello.
New version avaiable https://www.rarlab.com/rar/unrarsrc-5.7.3.tar.gz

**Comment by aawc** [comment]
Sorry for the delay in responding.

The version you linked to is available here: https://github.com/aawc/unrar/tree/v5.7.3
There's actually a new version available now: https://github.com/aawc/unrar/tree/v5.7.4

I'll be merging 5.7.4 into master soon.

**Comment by aawc** [comment]
Updated to v5.7.4 via #22
