### ISSUE TITLE
Request to review v6.0.3

### ISSUE THREAD

**Issue by aawc** [aawc/unrar#27]
@chrdavis -- since you landed a patch in this repository previously, would you be interested in reviewing the latest version on the `unrar` library?

I just landed `v6.0.3` here and would welcome a review from you (feel free to decline).
Sorry for not asking you about this before landing the new version of the library.

Most specifically, I ended up rolling back your changes from https://github.com/aawc/unrar/pull/23 so that the code here is an exact replica of the `unrar` library source from rarlab.com, but the corresponding CL in the Chromium repository will be unaffected.

Also, please let me know if you'd like to review https://chromium-review.googlesource.com/c/chromium/src/+/2634824

Thanks!

**Comment by chrdavis** [comment]
Thanks for the heads up.   Where can I make a PR to rarlab so the change sticks?

**Comment by aawc** [comment]
I think you'll need to send a patch to the maintainer directly at info@win-rar.com

**Comment by chrdavis** [comment]
Thanks.  I just sent them mail.
