### ISSUE TITLE
OSS-Fuzz build issue recently introduce due to duplicate variable declaration

### ISSUE THREAD

**Issue by DavidKorczynski** [aawc/unrar#30]
A recently commit introduced a double declaration of `SetAttrOnly` in `Extract.cpp`, this is currently causing OSS-Fuzz build issues https://oss-fuzz-build-logs.storage.googleapis.com/log-441dcd4d-726a-4c18-aa1b-6a9eca259d06.txt:

https://github.com/aawc/unrar/blob/487e5309e8fa0dd541fa55e75802aedfa11b1e26/extract.cpp#L778-L793

**Comment by aawc** [comment]
Fixed by #31
